//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAL.SqlCommands", typeof(SqlCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Orders(UserID,Price,OrderDate,Quantity,ProductID) values(@userId,@price,@date,@qty,@productId).
        /// </summary>
        public static string CREATE_ORDER {
            get {
                return ResourceManager.GetString("CREATE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into OrderDetails(OrderID,ProductID,Price,AvailableQTY) values(@orderId,@productId,@price,@qty).
        /// </summary>
        public static string CREATE_ORDERDETAILS {
            get {
                return ResourceManager.GetString("CREATE_ORDERDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into Products (Name,Color,UnitPrice,Size,Weight,IsDiscounted,SubcategoryID,Image) values (@newName,@newColor,@newUP,@size,@newWeight,@discount,@subcatID,@image).
        /// </summary>
        public static string CREATE_PRODUCT {
            get {
                return ResourceManager.GetString("CREATE_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Users where Email=@id.
        /// </summary>
        public static string CURRENT_USER {
            get {
                return ResourceManager.GetString("CURRENT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from Subcategories where ProductID=@id.
        /// </summary>
        public static string DELETE_FROM_SUBCATEGORIES {
            get {
                return ResourceManager.GetString("DELETE_FROM_SUBCATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from OrderDetails where OrderID=@idOd.
        /// </summary>
        public static string DELETE_ORDERDETAILS {
            get {
                return ResourceManager.GetString("DELETE_ORDERDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from Orders where OrderID=@idO.
        /// </summary>
        public static string DELETE_ORDERS {
            get {
                return ResourceManager.GetString("DELETE_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from Products where ProductID=@id.
        /// </summary>
        public static string DELETE_PRODUCT {
            get {
                return ResourceManager.GetString("DELETE_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 OrderID FROM Orders ORDER BY OrderID DESC.
        /// </summary>
        public static string GET_ORDERID {
            get {
                return ResourceManager.GetString("GET_ORDERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Name,UnitPrice,ProductID from Products where ProductID=@id.
        /// </summary>
        public static string GETPRODUCT_ORDER {
            get {
                return ResourceManager.GetString("GETPRODUCT_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Products.
        /// </summary>
        public static string SHOW_PRODUCTS {
            get {
                return ResourceManager.GetString("SHOW_PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select OrderDetails.OrderID,Products.Name,OrderDetails.Price,OrderDetails.AvailableQTY from OrderDetails join Orders on Orders.OrderID=OrderDetails.OrderID join Products on OrderDetails.ProductID=Products.ProductID where Orders.UserID=@id.
        /// </summary>
        public static string SHOW_USER_ORDERDETAILS {
            get {
                return ResourceManager.GetString("SHOW_USER_ORDERDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select OrderID,Price,OrderDate,Quantity from Orders join Users on Users.UserID=Orders.UserID where Users.Email=@id.
        /// </summary>
        public static string SHOW_USER_ORDERS {
            get {
                return ResourceManager.GetString("SHOW_USER_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Products set Color=@newColor where ProductID=@idC .
        /// </summary>
        public static string UPDATE_PRODUCT_color {
            get {
                return ResourceManager.GetString("UPDATE_PRODUCT_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Products set Name=@newName where ProductID=@idN .
        /// </summary>
        public static string UPDATE_PRODUCT_name {
            get {
                return ResourceManager.GetString("UPDATE_PRODUCT_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Products set UnitPrice=@newUP where ProductID=@idP .
        /// </summary>
        public static string UPDATE_PRODUCT_price {
            get {
                return ResourceManager.GetString("UPDATE_PRODUCT_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Products set Size=@newSize where ProductID=@idS .
        /// </summary>
        public static string UPDATE_PRODUCT_size {
            get {
                return ResourceManager.GetString("UPDATE_PRODUCT_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Products set Weight=@newWeight where ProductID=@idW .
        /// </summary>
        public static string UPDATE_PRODUCT_weight {
            get {
                return ResourceManager.GetString("UPDATE_PRODUCT_weight", resourceCulture);
            }
        }
    }
}
